### PR TITLE
Modified demo code for newer api that supports entt 3.3.0

### PR DESCRIPTION
**Pull request by GnikDroy**
You need to update the submodule of the imgui_entity_editor to point to a snapshot after the PR there has been merged to master.

I have updated entt's single include file manually from their master branch. Although, we should probably make a submodule for that as well.

### CODE REVIEW

**Comment by Green-Sky** [comment]
... almost forgot this one.
Same problems as the other pr: tabs vs spaces.
And while you are at it, pls update imgui_entt_entity_editor

**Comment by Green-Sky** [comment]
Any progress on this? since this is a PR from your fork, i can't edit it. So i would need to either merge into a tmp branch or redo it myself. :wave: 
...also, new entt version :smile:

**Comment by GnikDroy** [comment]
Sorry, I have been busy. I have allowed edits from maintainers, so that should allow you to directly push to my fork.

I will probably be busy for a few more weeks. It would be great if you could find time to work on this. : )

**Comment by Green-Sky** [comment]
so. at long last. Anyway, thank you for your contribution :heart: . Also let me know, where your project goes ;) .

**Pull request merged**
